---
title: "Course Title"
author: "[Mark Daku](www.markdaku.com), Ph.D. ([mark.daku@tcu.edu](mailto:mark.daku@tcu.edu))"
date: 'Term, YYYY - T/Tr Start-Finish, Room'
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
biblio-style: apalike
link-citations: yes
---

# Syllabus {-}
## Course Description {-}

What's this course about? (Probably just import this from a file - idea is to have all the boiler-plate stuff here)

## Course Objectives {-}

If necessary, a different section with information on the particular objectives of the course
(Again, import this from a file)

## General Course Information {-}

In general, I don't really believe in rules for students.  Do whatever you want, you are adults, but I do have rules for myself and I am pretty disciplined about them. I may break them if they conflict with other rules, or if I just feel like it, but don't count on it:

### Readings {-}
1. I will teach students who legitimately want to learn.  As such, I put in a number of safe-guards to make sure that the students in my classes have done their work before coming class. 

### Attendence {-}
1. I refuse to take attendence. It is my belief that you are adults and you want to learn (see above). I expect that if you must miss a class, it is because you have other priorities, and that you have weighed the cost/benefit of them accordingly. If you have a documented reason to miss class (e.g. a note from a doctor), then please let me know immediately and arrangements can be made.  Let me be clear: the only time I need to hear about you missing a class is if it was not a decision you made. If you choose to go on a ski trip, that's great! I hope you had fun, please don't tell me about it.  If you broke your leg on that ski trip and need to miss another class to go to get a cast, that's karma - but it's also a legitimate reason to miss a class and you should tell me. 

### E-mails {-}
1. I will not reply to e-mails on evenings or weekends.
2. I will not answer questions that are answered on the syllabus.
3. I will not answer e-mails about why you are going to miss a class / why you missed a class.  See `Attendence.'
4. I will not answer in-depth questions about course material by e-mail (I am available almost every day on campus to talk)
5. I will reply to e-mails within one business day. If you e-mail me on Monday at 8pm, you can expect an e-mail before Wednesday 9am.  If you e-mail me on Friday at 9am of a long weekend, you can expect an e-mail by the following Tuesday at 9am.

### Encrypted E-mails {-}
I am an advocate of internet privacy and I try to encourage everyone I know to take it seriously. One good way to ensure private communications is to encrpyt your e-mail. To encourage you to do this, I have the following additional rules:

1. I *will* reply to any e-mail, even if it breaks one or all of my rules above, if it is encrypted using PGP. 
2. I will always answer encrypted e-mails *first*, and I will process them with my personal e-mail (which means I will likely answer it faster, though there is no guarantee)

### Office Hours {-}
1. I hold office hours on Tuesday-Thursday between 1-2pm. I prioritize meeting with students who have set up appointments (you can do so [here](www.markdaku.com)), though I am obviously thrilled to chat with anyone who drops by during that time.
2. I will make arrangements to meet with students who cannot attend my office hours within one week of them e-mailing me. 
3. I will keep meetings to their scheduled time. 


### Classroom Environment {-}

1. I will not tolerate disruptive classroom behavior. However, I also believe you are adults who want to learn.  If you believe that the best way to do that is to sit in the back of the classroom and scroll through instagram, then go right ahead.  The exceptions are during exames, and if your actions are distracting to other students. Your actions always have to take into account that you are in a shared space.

2. I will ensure that all students have an equal opportunity to learn.  

3. Texas Christian University complies with the Americans with Disabilities Act and Section 504 of the Rehabilitation Act of 1973 regarding students with disabilities.  Eligible students seeking accommodations should contact the Coordinator of Services for Students with Disabilities in the Center for Academic Services located in Sadler Hall, 11. Accommodations are not retroactive, therefore, students should contact the Coordinator as soon as possible in the term for which they are seeking accommodations. Further information can be obtained from the Center for Academic Services, TCU Box 297710, Fort Worth, TX 76129, or at (817) 257-7486.   Adequate time must be allowed to arrange accommodations and accommodations are not retroactive; therefore, students should contact the Coordinator as soon as possible in the academic term for which they are seeking accommodations. Each eligible student is responsible for presenting relevant, verifiable, professional documentation and/or assessment reports to the Coordinator. Guidelines for documentation may be found at [http://www.acs.tcu.edu/DISABILITY.HTM](http://www.acs.tcu.edu/DISABILITY.HTM).

## Required Materials {-}
Course texts can be purchased at bookstore.  Wherever possible, material has been located and made avaialble for free. Links are within the text of the syllabus.

## Grades {-}

Your grade will be calculated based on the following: 
1. Assignment 1 (X%)
2. Assignment 2 (X%)
3. Assignment 3 (X%)
4. Assignment 4 (X%)

There will be an exam on DATE.  
Exam specifics.  
(All this should be imported from a file)

## Grade Appeals {-}
Errors of arithmetic, etc. will be fixed immediately during office hours with my sincere apologies.
Other inquiries will be considered if they are presented in writing, with a clear explanation for why you believe the grade does not relfect the work presented.  If I accept the petition, I will regrade the ENTIRE piece of work with a careful eye to detail.  Your grade may go **up** or **down** after this review, and there will be no more opportunities for appeal,

## Plagiarism & Cheating {-}
You will not survive my wrath. 
